title: Konnichiwa!
author: Pasupuleti Sai Harshavardhan
email: saihv18@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my personal blog . I write some stuff whenever I feel like it . Keep in touch for more interesting content!

# social links

github_username: hvplusultra18 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
