title: Konnichiwa!
author: Pasupuleti Sai Harshavardhan
email: saihv18@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Just a guy who writes his heart out.

# social links

github_username: hvplusultra18 # DO NOT include the @ character, or else the build will fail!
instagram_username: satoru_1801

show_excerpts: true # set to false to remove excerpts on the homepage
